// Instagram Reel teaser (1080x1920). Narration + beats come from teaser_build.json
// (generated by pipeline/teaser_tts.py from config/teaser.json); each beat plays a live
// moment of the main video's scene inside a landscape window.
import React from "react";
import {
  AbsoluteFill,
  interpolate,
  random,
  Sequence,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { Audio } from "@remotion/media";
import { createTikTokStyleCaptions, type Caption } from "@remotion/captions";
import teaserJson from "../teaser_build.json";
import teaserConfig from "../config/teaser.json";
import {
  config,
  meta,
  msToFrames,
  paragraphStartMs,
  segmentFrames,
  segments,
  type Word,
} from "./data";
import { SegmentScene } from "./components/SegmentScene";
import { TitleCard } from "./components/Cards";
import { body, C, display } from "./theme";

type Beat = {
  headline: string;
  text: string;
  show: {
    segment?: string;
    paragraph?: number;
    offset_ms?: number;
    title_card?: boolean;
  };
};
const teaser = teaserJson as unknown as {
  duration_seconds: number;
  paragraph_starts: number[];
  words: Word[];
  audio_file: string;
  beats: Beat[];
};

export const teaserFrames = () =>
  Math.ceil(teaser.duration_seconds * config.fps);

const W = 1080;
const WIN_H = Math.round((1080 * 1080) / 1920); // 608: 16:9 window at full width
const WIN_TOP = 560; // below the Instagram header safe zone
const clamp = { extrapolateLeft: "clamp", extrapolateRight: "clamp" } as const;

export const Teaser: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const starts = teaser.paragraph_starts.map(msToFrames);
  const beatAt = Math.max(0, starts.filter((s) => frame >= s).length - 1);
  const beat = teaser.beats[beatAt];
  const beatStart = starts[beatAt];
  const beatEnd = starts[beatAt + 1] ?? durationInFrames;
  const isLast = beatAt === teaser.beats.length - 1;

  const pop = spring({
    frame: frame - beatStart,
    fps,
    config: { damping: 14, stiffness: 170 },
  });
  const music = interpolate(
    frame,
    [0, 10, durationInFrames - 30, durationInFrames],
    [0, 0.22, 0.22, 0],
    clamp,
  );

  return (
    <AbsoluteFill style={{ backgroundColor: C.bg }}>
      <AbsoluteFill
        style={{
          background: `radial-gradient(ellipse at 50% 38%, #1a2233 0%, ${C.bg} 62%)`,
        }}
      />

      {/* brand line */}
      <div
        style={{
          position: "absolute",
          top: 230,
          width: W,
          textAlign: "center",
          fontFamily: body,
          fontWeight: 700,
          fontSize: 30,
          letterSpacing: 10,
          color: C.accent,
        }}
      >
        {meta.title}
      </div>

      {/* beat headline */}
      <div
        style={{
          position: "absolute",
          top: 285,
          left: 60,
          right: 60,
          height: 250,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          textAlign: "center",
          fontFamily: display,
          fontWeight: 700,
          fontSize: 104,
          lineHeight: 1.0,
          color: C.ink,
          textTransform: "uppercase",
          opacity: beatAt === 0 ? 1 : interpolate(pop, [0, 1], [0, 1]),
          transform: `scale(${beatAt === 0 ? 1 : interpolate(pop, [0, 1], [0.9, 1])})`,
        }}
      >
        {beat.headline}
      </div>

      {/* landscape window playing a moment from the main video */}
      <div
        style={{
          position: "absolute",
          top: WIN_TOP,
          left: 0,
          width: W,
          height: WIN_H,
          overflow: "hidden",
          borderTop: `3px solid ${C.red}`,
          borderBottom: `3px solid ${C.red}`,
        }}
      >
        {teaser.beats.map((b, i) => (
          <Sequence
            key={i}
            from={starts[i]}
            durationInFrames={(starts[i + 1] ?? durationInFrames) - starts[i]}
          >
            <BeatWindow beat={b} />
          </Sequence>
        ))}
        {/* cut flash */}
        <AbsoluteFill
          style={{
            background: "#fff",
            pointerEvents: "none",
            opacity:
              beatAt === 0
                ? 0
                : interpolate(frame - beatStart, [0, 5], [0.35, 0], clamp),
          }}
        />
      </div>

      <TeaserCaptions words={teaser.words} />

      {/* progress + CTA */}
      <div
        style={{
          position: "absolute",
          bottom: 400,
          width: W,
          display: "flex",
          justifyContent: "center",
          gap: 10,
        }}
      >
        {teaser.beats.map((_, i) => (
          <div
            key={i}
            style={{
              width: 64,
              height: 6,
              borderRadius: 3,
              background:
                i < beatAt ? C.ink : i === beatAt ? C.accent : "#2a3242",
              opacity:
                i === beatAt
                  ? interpolate(frame, [beatStart, beatEnd], [0.6, 1], clamp)
                  : 1,
            }}
          />
        ))}
      </div>
      <div
        style={{
          position: "absolute",
          bottom: 320,
          width: W,
          textAlign: "center",
          fontFamily: body,
          fontWeight: 700,
          fontSize: isLast ? 46 : 30,
          color: isLast ? C.ink : C.dim,
          letterSpacing: isLast ? 1 : 4,
          textTransform: "uppercase",
          transform: `scale(${isLast ? interpolate(pop, [0, 1], [0.9, 1]) : 1})`,
        }}
      >
        ▶ {teaserConfig.cta}
      </div>

      <TeaserGrain />
      <Audio src={staticFile(teaser.audio_file)} />
      <Audio src={staticFile("music/music.mp3")} loop volume={music} />
    </AbsoluteFill>
  );
};

/** Plays the main-video scene for a beat, starting at the chosen paragraph moment. */
const BeatWindow: React.FC<{ beat: Beat }> = ({ beat }) => {
  const frame = useCurrentFrame();
  const punch = interpolate(frame, [0, 45], [1.06, 1], {
    ...clamp,
    easing: (t) => 1 - (1 - t) ** 3,
  });
  if (beat.show.title_card) {
    return (
      <div
        style={{
          width: 1920,
          height: 1080,
          transform: `scale(${WIN_H / 1080})`,
          transformOrigin: "0 0",
          position: "relative",
          flexShrink: 0,
        }}
      >
        <Sequence from={-60}>
          <TitleCard
            durationInFrames={config.title_card_seconds * config.fps + 400}
          />
        </Sequence>
      </div>
    );
  }
  const seg = segments.find((s) => s.id === beat.show.segment);
  if (!seg) return null;
  const offset = msToFrames(
    paragraphStartMs(seg, beat.show.paragraph ?? 0) +
      (beat.show.offset_ms ?? 0),
  );
  return (
    <div
      style={{
        width: 1920,
        height: 1080,
        position: "relative",
        flexShrink: 0,
        transformOrigin: "0 0",
        transform: `scale(${(WIN_H / 1080) * punch}) translate(${((1 - punch) * -960) / punch}px, ${((1 - punch) * -540) / punch}px)`,
      }}
    >
      <Sequence from={-offset} durationInFrames={segmentFrames(seg)}>
        <SegmentScene
          seg={seg}
          durationInFrames={segmentFrames(seg)}
          embedded
        />
      </Sequence>
    </div>
  );
};

/** Large phone-first captions: 2–5 words at a time, current word in amber. */
const TeaserCaptions: React.FC<{ words: Word[] }> = ({ words }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const pages = React.useMemo(
    () =>
      createTikTokStyleCaptions({
        captions: words.map((w, i) => ({
          text: (i === 0 ? "" : " ") + w.text,
          startMs: w.startMs,
          endMs: w.endMs,
          timestampMs: w.startMs,
          confidence: null,
        })) as Caption[],
        combineTokensWithinMilliseconds: 900,
      }).pages,
    [words],
  );
  const ms = (frame / fps) * 1000;
  const page = pages.find(
    (p) => ms >= p.startMs && ms < p.startMs + p.durationMs + 200,
  );
  if (!page) return null;
  return (
    <div
      style={{
        position: "absolute",
        top: WIN_TOP + WIN_H + 64,
        left: 70,
        right: 70,
        height: 300,
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "center",
        textAlign: "center",
      }}
    >
      <div
        style={{
          fontFamily: body,
          fontWeight: 800,
          fontSize: 76,
          lineHeight: 1.22,
          color: C.ink,
          textShadow: "0 4px 18px #000",
        }}
      >
        {page.tokens.map((t, i) => (
          <span
            key={i}
            style={{
              color: ms >= t.fromMs && ms < t.toMs + 60 ? C.accent : C.ink,
              whiteSpace: "pre-wrap",
            }}
          >
            {t.text}
          </span>
        ))}
      </div>
    </div>
  );
};

const TeaserGrain: React.FC = () => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill
      style={{
        backgroundImage: `url(${staticFile("fx/grain.png")})`,
        backgroundPosition: `${Math.floor(random(`tx${frame}`) * 512)}px ${Math.floor(random(`ty${frame}`) * 512)}px`,
        opacity: 0.05,
        mixBlendMode: "overlay",
        pointerEvents: "none",
      }}
    />
  );
};
